global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: main-orchestrator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["main-orchestrator:8081"]

  - job_name: vector-data-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["vector-data-service:8082"]
